### ISSUE TITLE
forum.kaosx.us gives a 500 error

### ISSUE THREAD

**Issue by RJVB** [KaOSx/kaosx.github.io#11]
Note sure where else to report this: forum.kaosx.us has been giving me a http 500 failure since yesterday.

A bit annoying as it apparently has the only relevant discussion of the systemd freezing I'm seeing very early in the boot process following an error message about nsdelegate, after doing long-overdue upgrades on my VM.

**Comment by demmm** [comment]
This is for the website, please use the proper bug reporting for systemd.
Forum being down:
https://plus.google.com/u/0/110986511642497346750/posts/Crvhwp6z2jz

Bug reports for core:
https://kaosx.us/docs/bugs/

**Comment by RJVB** [comment]
> This is for the website, please use the proper bug reporting for systemd.

What does systemd have to do with the support forum?

> Forum being down:
> https://plus.google.com/u/0/110986511642497346750/posts/Crvhwp6z2jz

That post is about a "custom KaOS first run wizard in QML", don't see the relevance there either.

I just cross my fingers that the message has been received and the forum will come up again before I feel like booting my KaOS VM again.

R.

**Comment by demmm** [comment]
No idea what you are trying to report, but your initial report is about systemd:
>A bit annoying as it apparently has the only relevant discussion of the systemd freezing

Any KaOS app also has it's own github repo & bug tracker, so please stop with this thread, complete irrelevant.
