### ISSUE TITLE
insructitional should be instructional

### ISSUE THREAD

**Issue by yatesco** [KaOSx/kaosx.github.io#13]
Currently found on the home page of https://kaosx.us.

The only reference was in '_screens/index.html', but that was only in a commit - it doesn't appear in the branch, so I can't do a PR ;-).

<img width="1367" alt="screenshot 2018-09-29 at 18 13 14" src="https://user-images.githubusercontent.com/181469/46248616-77e94880-c413-11e8-8be8-cdd198a1f9be.png">

**Comment by demmm** [comment]
The file is here:
https://github.com/KaOSx/kaosx.github.io/blob/master/_includes/screens.html
as referenced here:
https://github.com/KaOSx/kaosx.github.io/blob/master/index.html#L86
Let me know if you want to have credit for this (doing a pull request).

**Comment by yatesco** [comment]
If it isn’t fixed by the time I get to it tomorrow then I’ll do a PR, but I’m not bothered about the credit ;-).
