### ISSUE TITLE
Incorrect configuration of flatpak in documentation

### ISSUE THREAD

**Issue by haggen88** [KaOSx/kaosx.github.io#17]
A wrong repository appears in the documentation to configure [flatpak](https://kaosx.github.io/docs/flatpak/) 

When running:   
> flatpak remote-add --if-not-exists gnome https://sdk.gnome.org/gnome.flatpakrepo

Show this error:  
> error: Can't load uri https://sdk.gnome.org/gnome.flatpakrepo: Error resolving “sdk.gnome.org”: Name or service not known

GNOME SDK are current [hosted](https://wiki.gnome.org/Apps/Evolution/Flatpak) on the Flathub, so the correct instructions would be:

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

**Comment by demmm** [comment]
Thanks for reporting outdated links.
If you fork the [website repo](https://github.com/KaOSx/kaosx.github.io), make the correction and open a pull request, you will be properly credited (forever) with making the needed changes.
https://github.com/KaOSx/kaosx.github.io/blob/master/_docs/flatpak.md
If not planning on doing that, please note so here, then I will fix this bug.

**Comment by haggen88** [comment]
I leave it in your hands.

Best regards
