### ISSUE TITLE
installing

### ISSUE THREAD

**Issue by ksso00** [KaOSx/kaosx.github.io#7]
maybe it had been already reported, however for be sure, here it is

at gpt manual partition this message error 

Error Boost.Python en el proceso "bootldr".
<class 'subprocess.CalledProcessError'>
Command 'grub-install /dev/sda' returned non-zero exit status 1.
Traceback:
  File "/usr/lib/calamares/modules/bootldr/main.py", line 222, in run
    install_bootloader(boot_loader, fw_type)

  File "/usr/lib/calamares/modules/bootldr/main.py", line 208, in install_bootloader
    check_target_env_call(["grub-install", install_path])

  File "<string>", line 2, in <module>

https://gist.github.com/17a5082c370b5a8ef91aceefb93a7467
https://pastebin.com/D4PH1xWG

if it is an user error or does not apply just close it
thanks

**Comment by demmm** [comment]
This is 99% sure user error, but to know for sure will need to see the installation.log and disk layout, see:
https://kaosx.us/docs/#info-to-provide-for-installation-issues

**Comment by demmm** [comment]
Closing the issue here though, since this has zero to do with the KaOS website.
Open issue in the correct, installer section:
https://kaosx.us/bugs
