### ISSUE TITLE
Document the KaOS replacement of DKMS

### ISSUE THREAD

**Issue by ShalokShalom** [KaOSx/kaosx.github.io#9]
There is no dkms in the repos and typical dkms packages so as Virtualbox are packaged without, so how can I develop packages like that?

**Comment by demmm** [comment]
Nothing to do with the website, nor with any KaOS package, dkms is only needed if a distro does not rebuild kernel modules for kernel updates.  No such thing happens in KaOS.

**Comment by ShalokShalom** [comment]
If that happens in another package, which is supposed to get ported, what to do?
Like, if I aim to port an Arch package, which use dkms?

Can I simply leave it out?
This might be worth a mention then as well.

**Comment by demmm** [comment]
This is for the KaOS website, not for helping creating packages or using KCP.

**Comment by ShalokShalom** [comment]
https://kaosx.us/docs/package/
